### ISSUE TITLE
Definitely an interesting idea, but there's a flaw...

### ISSUE THREAD

**Issue by SeisuAkimaro** [leyiang/morse-battle#1]
Upon opening the index.html file the screen only displays white. I'll scan through the html and javascript code to see if I can find it, but just wanted to make sure it was documented :3

**Comment by leyiang** [comment]
That's because I used [js import syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), so u can't start the app by open index.html. To open this app, try install a web server and [deploy this](https://stackoverflow.com/a/62533794/11134160). Any web server would work.
